apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: fipaaa/ambulance-wl-webapi
  newName: fipaaa/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260407.1050 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: fipaaa/ambulance-ufe
  newName: fipaaa/ambulance-ufe # {"$imagepolicy": "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260407.1404 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
