apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: fpauco-ambulance-wl
  includeSelectors: true
  includeTemplates: true
- pairs:
    wac-fiit.github.io/project: fpauco-ambulance-wl
  includeSelectors: false
  includeTemplates: true

resources:
- ../../../apps/fpauco-ambulance-ufe
- ../../../apps/fpauco-ambulance-webapi


components:
- ../../../components/version-release