apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: fpauco-ambulance-ufe-content
spec:
  microFrontend: fpauco-ambulance-ufe
  element: fpauco-ambulance-wl-app
  attributes:
    - name: base-path
      value: /fpauco-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?fpauco-ambulance-wl(/.*)?$"